project:
    resource: "@ProjectBundle/Controller/"
    type:     annotation
    prefix:   /

timesheet:
    resource: "@TimesheetBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
